import React,{useState}from"react";
import{SafeAreaView,View,Text,StyleSheet,TouchableOpacity,ScrollView,TextInput,Image}from"react-native";
import{StatusBar}from"expo-status-bar";
import{Ionicons}from"@expo/vector-icons";
const C={bg:"#0A0712",card:"#151021",violet:"#7C3AED",blue:"#38BDF8",text:"#F7F4FF",muted:"#A9A1B8",line:"#282039"};
const stories=[["Joseph",12],["Aminata",47],["Kevin",33],["Mariam",44]];
const posts=[["Aminata",47,"Une nouvelle journée, une nouvelle énergie. ✨","https://images.unsplash.com/photo-1517841905240-472988babdf9?w=900",248,32],["Kevin",33,"Construire. Apprendre. Recommencer. 🚀","https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=900",184,21]];
const avatar=n=>`https://i.pravatar.cc/120?img=${n}`;
function Header(){return <View style={s.header}><View><Text style={s.logo}>ZELYVO</Text><Text style={s.tag}>Connect. Share. Be You.</Text></View><View style={s.icon}><Ionicons name="notifications-outline" size={23} color={C.text}/></View></View>}
function Stories(){return <View><Text style={s.section}>Stories</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{stories.map(([n,i])=><View style={s.story} key={n}><View style={s.ring}><Image source={{uri:avatar(i)}} style={s.storyImg}/></View><Text style={s.storyName}>{n}</Text></View>)}</ScrollView></View>}
function Post({p}){const[l,setL]=useState(false);return <View style={s.post}><View style={s.row}><Image source={{uri:avatar(p[1])}} style={s.avatar}/><View style={{flex:1}}><Text style={s.name}>{p[0]}</Text><Text style={s.handle}>@{p[0].toLowerCase()} · maintenant</Text></View><Ionicons name="ellipsis-horizontal" size={20} color={C.muted}/></View><Text style={s.postText}>{p[2]}</Text><Image source={{uri:p[3]}} style={s.postImage}/><View style={s.actions}><TouchableOpacity style={s.action} onPress={()=>setL(!l)}><Ionicons name={l?"heart":"heart-outline"} size={23} color={l?"#F43F5E":C.text}/><Text style={s.actionText}>{p[4]+(l?1:0)}</Text></TouchableOpacity><View style={s.action}><Ionicons name="chatbubble-outline" size={21} color={C.text}/><Text style={s.actionText}>{p[5]}</Text></View><View style={s.action}><Ionicons name="paper-plane-outline" size={21} color={C.text}/><Text style={s.actionText}>Partager</Text></View></View></View>}
function Home(){return <><Header/><ScrollView contentContainerStyle={s.content}><Stories/><View style={s.compose}><Ionicons name="add-circle-outline" size={24} color={C.blue}/><Text style={s.composeText}>Quoi de neuf ? Partage quelque chose...</Text></View>{posts.map((p,i)=><Post p={p} key={i}/>)}</ScrollView></>}
function Discover(){return <ScrollView contentContainerStyle={s.content}><Text style={s.title}>Découvrir</Text><View style={s.search}><Ionicons name="search" size={20} color={C.muted}/><TextInput placeholder="Rechercher sur ZELYVO" placeholderTextColor={C.muted} style={s.input}/></View><Text style={s.section}>Suggestions pour toi</Text>{stories.map(([n,i])=><View style={s.user} key={n}><Image source={{uri:avatar(i)}} style={s.avatar}/><View style={{flex:1}}><Text style={s.name}>{n}</Text><Text style={s.handle}>Créateur ZELYVO</Text></View><View style={s.follow}><Text style={s.followText}>Suivre</Text></View></View>)}</ScrollView>}
function Messages(){return <ScrollView contentContainerStyle={s.content}><Text style={s.title}>Messages</Text>{stories.map(([n,i])=><View style={s.user} key={n}><Image source={{uri:avatar(i)}} style={s.avatar}/><View style={{flex:1}}><Text style={s.name}>{n}</Text><Text style={s.handle}>Appuie pour ouvrir la conversation</Text></View><Ionicons name="chevron-forward" size={20} color={C.muted}/></View>)}</ScrollView>}
function Profile(){return <ScrollView contentContainerStyle={s.content}><View style={s.profile}><Image source={{uri:avatar(12)}} style={s.profileAvatar}/><Text style={s.profileName}>Joseph Putu</Text><Text style={s.handle}>@joseph · ZELYVO</Text><Text style={s.bio}>Connect. Share. Be You. ✨</Text><View style={s.stats}><View><Text style={s.statN}>24</Text><Text style={s.handle}>Publications</Text></View><View><Text style={s.statN}>1.2K</Text><Text style={s.handle}>Abonnés</Text></View><View><Text style={s.statN}>386</Text><Text style={s.handle}>Abonnements</Text></View></View></View><View style={s.edit}><Text style={s.followText}>Modifier le profil</Text></View></ScrollView>}
function Nav({tab,setTab}){let a=[["home","Accueil"],["compass","Découvrir"],["add-circle","Publier"],["chatbubbles","Messages"],["person","Profil"]];return <View style={s.nav}>{a.map(([ic,n],i)=><TouchableOpacity key={n} onPress={()=>setTab(i)} style={s.navItem}><Ionicons name={ic} size={22} color={tab===i?C.blue:C.muted}/><Text style={[s.navText,tab===i&&{color:C.blue}]}>{n}</Text></TouchableOpacity>)}</View>}
export default function App(){const[t,setT]=useState(0);return <SafeAreaView style={s.safe}><StatusBar style="light"/>{[<Home/>,<Discover/>,<Home/>,<Messages/>,<Profile/>][t]}<Nav tab={t} setTab={setT}/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{padding:18,paddingBottom:12,flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderBottomWidth:1,borderBottomColor:C.line},logo:{fontSize:25,fontWeight:"900",letterSpacing:1.5,color:C.text},tag:{fontSize:10,color:C.muted},icon:{width:42,height:42,borderRadius:21,backgroundColor:C.card,alignItems:"center",justifyContent:"center"},content:{padding:16,paddingBottom:105},section:{fontSize:17,fontWeight:"800",color:C.text,marginVertical:12},story:{width:76,alignItems:"center",marginRight:10},ring:{width:64,height:64,borderRadius:32,borderWidth:2,borderColor:C.violet,padding:3},storyImg:{width:56,height:56,borderRadius:28},storyName:{fontSize:11,color:C.muted,marginTop:6},compose:{marginTop:18,padding:15,borderRadius:16,backgroundColor:C.card,flexDirection:"row",alignItems:"center",gap:10},composeText:{color:C.muted,flex:1},post:{backgroundColor:C.card,borderRadius:18,padding:14,marginTop:14},row:{flexDirection:"row",alignItems:"center",gap:10},avatar:{width:42,height:42,borderRadius:21},name:{color:C.text,fontWeight:"800"},handle:{color:C.muted,fontSize:12,marginTop:2},postText:{color:C.text,fontSize:15,lineHeight:21,marginVertical:12},postImage:{width:"100%",height:300,borderRadius:14},actions:{flexDirection:"row",justifyContent:"space-between",paddingTop:12},action:{flexDirection:"row",alignItems:"center",gap:6},actionText:{color:C.muted,fontSize:12},title:{fontSize:29,fontWeight:"900",color:C.text,marginBottom:18},search:{height:50,borderRadius:15,backgroundColor:C.card,flexDirection:"row",alignItems:"center",paddingHorizontal:14,gap:8},input:{flex:1,color:C.text},user:{backgroundColor:C.card,padding:13,borderRadius:15,marginBottom:10,flexDirection:"row",alignItems:"center",gap:11},follow:{backgroundColor:C.violet,paddingVertical:9,paddingHorizontal:17,borderRadius:20},followText:{color:"white",fontWeight:"800"},profile:{alignItems:"center",paddingTop:20},profileAvatar:{width:104,height:104,borderRadius:52,borderWidth:3,borderColor:C.violet},profileName:{color:C.text,fontSize:24,fontWeight:"900",marginTop:12},bio:{color:C.text,marginTop:10},stats:{flexDirection:"row",gap:38,marginTop:24},statN:{color:C.text,fontSize:18,fontWeight:"900",textAlign:"center"},edit:{marginTop:24,borderWidth:1,borderColor:C.line,padding:13,borderRadius:14,alignItems:"center"},nav:{position:"absolute",bottom:0,left:0,right:0,height:78,backgroundColor:"#100C19",borderTopWidth:1,borderTopColor:C.line,flexDirection:"row",justifyContent:"space-around",paddingTop:10},navItem:{alignItems:"center",flex:1},navText:{fontSize:10,color:C.muted,marginTop:4}});
